fix tooltip cutoff, remove linkability of thumbnail
OtterClam/otto-app pull request #412
Opened 2023-04-06 20:33 UTC by eonwarped

The link doesn't really behave as expected (esp when using multi-equip).

2023-04-06 21:07 UTC, eonwarped commented
it's not perfect because the arrow part of the tooltip doesn't align anymore, but that is proving to be a lot trickier. maybe i can style to remove it entirely though

2023-04-07 02:12 UTC, pyc92 commented
> The link doesn't really behave as expected (esp when using multi-equip).
I don't really understand what you meant. Could you please explain this more or provide a screenshot?

2023-04-07 02:49 UTC, eonwarped commented
> > The link doesn't really behave as expected (esp when using multi-equip).
> 
> I don't really understand what you meant. Could you please explain this more or provide a screenshot?

<img width="1318" alt="Screenshot 2023-04-06 at 10 47 13 PM" src="https://user-images.githubusercontent.com/34953718/230531000-15f2a649-6f09-48b0-b0df-585853e5a677.png">
<img width="1400" alt="Screenshot 2023-04-06 at 10 47 24 PM" src="https://user-images.githubusercontent.com/34953718/230531005-3318b396-de15-45c4-9502-547802a53261.png">

Second image shows what happens when clicking, the url changes but we are still selecting for the previous otter. So maybe I can disable it when it's used in this modal but keep link in my-items view.

2023-04-07 03:00 UTC, eonwarped commented
Added style to remove the arrow part, and restored link for my items view.

2023-04-07 03:10 UTC, pyc92 commented
Okay, I understand. However, why do we need to overwrite the tooltip position? I think react-tooltip already handles it quite well.

2023-04-07 03:13 UTC, eonwarped commented
Here's the before and after:

<img width="858" alt="Screenshot 2023-04-06 at 11 11 40 PM" src="https://user-images.githubusercontent.com/34953718/230533611-2e91528e-bcba-4d0e-8efc-a6acd45c142b.png">
<img width="700" alt="Screenshot 2023-04-06 at 11 12 12 PM" src="https://user-images.githubusercontent.com/34953718/230533613-1cee8995-072d-4a2f-a7a3-9f5dda2b547f.png">

I think it's specifically needed for this view because of the small frame, my items is probably fine. I removed the arrow because otherwise it doesn't point to the bubble when it gets moved, and is quite hard to customize the way we want.

2023-04-07 03:14 UTC, pyc92 requested changes

2023-04-07 03:14 UTC, pyc92 commented on src/components/ItemCell/index.tsx
>                <StyledOttoLink onClick={e => e.stopPropagation()}>
```suggestion
              <StyledOttoLink as="span">
```

I this case, it's not a link anymore.

2023-04-07 03:17 UTC, eonwarped commented on src/components/ItemCell/index.tsx
>                <StyledOttoLink onClick={e => e.stopPropagation()}>
Done

2023-04-07 03:19 UTC, eonwarped commented
For referecnce, taken from https://reacttooltip.github.io/react-tooltip/#:~:text=Type%20something...%27%20/%3E%20%0A%3C/ReactTooltip%3E-,Override,-position

2023-04-07 03:29 UTC, pyc92 commented
@eonwarped 

Could you try using `ReactDOM.createPortal` to solve the issue? I haven't dig into it yet, but I guess the problem stems from where we rendered the tooltip element. Therefore, createPortal should be able to resolve the issue. If it's not possible, then the current solution is ok for now.

2023-04-07 03:34 UTC, eonwarped commented
> @eonwarped
> 
> Could you try using `ReactDOM.createPortal` to solve the issue? I haven't dig into it yet, but I guess the problem stems from where we rendered the tooltip element. Therefore, createPortal should be able to resolve the issue. If it's not possible, then the current solution is ok for now.

I actually tried that first, but it didn't work when I put it to #modalRoot , it just disappeared. But it's possible I messed it up or should have used a different element.

2023-04-07 07:54 UTC, pyc92 approved these changes

2023-04-07 07:54 UTC, merged