feat: use the new contract to roll dices
OtterClam/otto-app pull request #85
Opened 2022-07-08 15:48 UTC by pyc92

2022-07-09 04:07 UTC, 0xthk requested changes

2022-07-09 04:07 UTC, 0xthk commented on src/hooks/useDiceRoller.ts
> +      const tx = await connectContractToSigner(ottoHellDiceRoller, {}, library).roll()
need pass otto id, amount

2022-07-11 08:16 UTC, d0c0q approved these changes

2022-07-11 08:23 UTC, 0xthk approved these changes

2022-07-11 08:23 UTC, merged